@echo off
cls
echo       ---------------------------------------------------------------
echo       -Yes, you know it's true --- Lemmings cracked by LUZIE and DOS-
echo       -                                                             -
echo       -Only the best can survive... the first ever PC Crack by LUZIE-
echo       -                                                             -
echo       -      Attention: HARD DISK INSTALLATION IS NECESSARY !!      -
echo       -                                                             -
echo       -   I'm very sorry, but this crack DOESN'T run with DOS 3.x   -
echo       -  because this versions don't support the ATTRIB -h command  -
echo       -                                                             -
echo       -HATINGS! goto all absolutely BRAINLESS Shit Virus Programmers-
echo       ---------------------------------------------------------------
pause
attrib -h -a russell.dat
del russell.dat
copy LUZIE.!!! russell.dat
call lemming2