@Echo Off
Cls
Echo Ъ
Echo                            мммммммкммммкммммкммммммм
Echo                            ммммммм╪         хммммммм
Echo Ъ
Echo                           JME Engineering pr└sentiert:
Echo Ъ
Echo Ъ
Echo Ъ
Echo         зддбдды ©            зддддддд©                 д©            здд
Echo            Ё    цдд© здд©    Ё       Ё ©   з зддд©зддд©дед      здд©дед
Echo            Ё    Ё  Ё цдды    Ё    здбы Ё   Ё цдддыюддд© Ё       Ё  Ё Ё
Echo           ды    ы  ю юдд     юдддды ю  юддда юддд юддды юдды    юдды Ё
Echo Ъ
Echo         ©   зд       з     ©     з         здддд©          д©  д©
Echo         Ё зды  ©   з з бдд©Ё  зд  зддд©    Ё     зддд©зддд©дед  Ё   зддд©
Echo         цдад©  Ё Ё Ё Ё Ё   Ёзда©  юддд©    Ё     зддд╢юддд© Ё   Ё   цддды
Echo         ы   юд юдады ы ы   аы  ю  юддды    юддддыюдддаюддды юддыюддыюддд
Echo    Ъ
Echo  Ъ
Echo  Ъ
Echo  Ъ
Echo  Ъ
Echo  Ъ
Echo                      Programm wird geladen  -  bitte warten
KW %1 %2 %3 %4 %5
