 ____________________________________________________________________________

    PLEASE FILL THIS OUT (READABLE) AND SEND IT TO ONE OF THESE ADRESSES

                   P.Schnitzler                    J.Herrmann
                  Heintgesweg 57       oder     Lorenz-G”rtz-Str.23
              D-4050 M”nchengladbach 2       D-4050 M”nchengaldbach 2

                                   G E R M A N Y
 ____________________________________________________________________________




                      B R E A K I N - REGISTRATION




 [ ]  BREAKIN............................. $15 (foreign countries)

            Shipping & Handling (INCL.)


             Total enclosed __________


  IMPORTANT! Circle disk size:  5.25  OR  3.5

  CPU: 286  386  486

  Is this your first order from ASG?   YES   NO

          Name: _______________________________________________

       Address: _______________________________________________

  City, ST Zip: ___________________________________ Phone: _________________


  Payment by: [ ] Money order




            .............       ........................
                Date                   Signature

 ___________________________________________________________________________

                        THE ACIDMAN OF SCORE GROUP
 ___________________________________________________________________________

