 ____________________________________________________________________________

   FORMULAR GUT LESBAR AUSFöLLEN UND AN EINE DER FOLGENDEN ADRESSE SCHICKEN

                   P.Schnitzler                    J.Herrmann
                  Heintgesweg 57       oder     Lorenz-Gîrtz-Str.23
              D-4050 Mînchengladbach 2       D-4050 Mînchengaldbach 2
 ____________________________________________________________________________


                      B R E A K I N - REGISTRIERUNG



   Hiermit mîchte ich mich als Benutzer Ihres Spiels Breakin registrieren
   lassen !

   Der Betrag von 20.- DM (DEUTSCHLAND) 15.- $ (AUSLAND)

                                        
      ( ) ist diesem Schreiben beigefögt.


   Ich habe folgenden Rechner : 286 386 486

   Ist das ihre erste Registrierung bei ASG ?   JA    NEIN

   Ich wÅnsche das registrierte Programm auf

      ( ) 5.25" - Diskette

      ( ) 3.5"  - Diskette

   ABSENDER :

                Name   :____________________________________

                Stra·e :____________________________________

                PLZ/Ort:____________________________________

                Telefon:____________________________________


            .............       ........................
             Datum               Unterschrift

 ___________________________________________________________________________

                        THE ACIDMAN OF SCORE GROUP
_____________________________________________________________________________