vpic phaze.lbm /w
echo off
cls
echo			   PHAZE 101 Presents .. PRINCE OF PERSIA
echo			  ++++++++++++++++++++++++++++++++++++++++
echo.
echo		       IMPORTED BY ..	    TERMINATOR / PHAZE 101  &
echo					    EMPEROR / SKID ROW MALTA ..
echo.
echo			   PHAZE 101 & SKID ROW are full members of ...
echo				PIRATES NETWORX INTERNATIONAL.
echo.
echo                  Watch out for loads of other new releases from us!
echo.
echo			   If you dare to contact us then write to :
echo.
echo			  PHAZE 101 , PO BOX 529 , VALLETTA , MALTA .
echo.
echo		    ******************************************************
echo		    * PHAZE 101 .. what we build will NEVER be destroyed *
echo		    ******************************************************
echo.
echo.
pause
prince
